---
description: >
  IOT-BASED FOOD GRAIN STORAGE MONITORING SYSTEM FOR SILOS is a system designed using edge computers / devices, The main objective of the system is to reduce the food grain wastage that is currently a problem in the food sector across India
geekdocToC: 3
geekdocTagsToMenu: true

geekdocSearch: true
geekdocSearchShowParent: true

geekdocImageLazyLoading: true
geekdocDarkModeDim: false